feat: provide imageproperty file (#86410)

diff --git a/ci-job-template.yml b/ci-job-template.yml
--- a/ci-job-template.yml
+++ b/ci-job-template.yml
@@ -717,6 +717,52 @@ jobs:
     displayName: "Publish project image"
     #enabled: false
 
+  # Generate a build information file and push it as a pipeline artifact.
+  - task: Bash@3
+    displayName: Create image overview
+    timeoutInMinutes: 5
+    env:
+      REGISTRY: ${{ parameters.acr }}
+    inputs:
+      targetType: "inline"
+      script: |
+        #!/bin/bash
+        set -e
+
+        ###############################################################
+        # Script Parameters                                           #
+        ###############################################################
+
+        # Create a temporary directory with a unique name
+        TMP_CUSTOM_DIR=$(mktemp -d -t ci-iom-XXXXXXXXXX)
+        IMAGE_PROPERTIES_FILE="${TMP_CUSTOM_DIR}/imageProperties.yaml"
+
+        ###############################################################
+        # Script                                                      #
+        ###############################################################
+
+        REGISTRY=${REGISTRY}
+        IMAGE_NAME=$(cat $PIPELINE_WORKSPACE/project-image-name.txt)
+        TAG=$(cat $PIPELINE_WORKSPACE/project-image-tag.txt)
+
+        # Write the repository name and tag to the imageProperties file
+        # Generate YAML file
+        cat <<EOF > ${IMAGE_PROPERTIES_FILE}
+        images:
+          - type: iom
+            tag: ${TAG}
+            name: ${IMAGE_NAME}
+            registry: ${REGISTRY}
+        EOF
+
+        # Print the contents of the imageProperties file
+        echo "###### File ${IMAGE_PROPERTIES_FILE} ######"
+        cat ${IMAGE_PROPERTIES_FILE}
+        echo "###### File end ######"
+
+        # Upload the imageProperties file as an artifact
+        echo "##vso[artifact.upload containerfolder=image;artifactname=image_artifacts]${IMAGE_PROPERTIES_FILE}"
+
   - ${{ if not(eq(parameters.postHookTemplate, '')) }}:
     - template: ${{ parameters.postHookTemplate }}
   
@@ -729,3 +775,16 @@ jobs:
     timeoutInMinutes: 5
     displayName: Cleanup Minikube
     condition: always()
+
+  # Clean up all Docker resources generated by the build.
+  - task: Bash@3
+    displayName: Docker Cleanup
+    timeoutInMinutes: 10
+    condition: always()
+    inputs:
+      targetType: "inline"
+      script: |
+        # Stop all containers
+        if [[ -n $(docker container ls -a -q) ]]; then docker container stop $(docker container ls -a -q); fi
+        # Remove all unused containers, networks, images and volumes.
+        docker system prune -a -f --volumes
